### ISSUE TITLE
Missing the information in "About" field.

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services.ko-KR#159]
Missing the Link to "Github Pages"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by VietTran0302** [comment]
Hi,

Please refer the below screenshot.
![image](https://user-images.githubusercontent.com/64255878/168539882-b3b57bd2-2680-4a6c-a902-038b3f172917.png)

**Comment by stonezy123** [comment]
not loclization issue

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/185028614-927288d9-0c81-4591-b5e8-7eeed3d0915f.png)
 
add it.
